package com.zqr.localchat.network

import android.content.ContentResolver
import android.net.Uri
import android.util.Log
import com.zqr.localchat.crypto.Crypto
import com.zqr.localchat.data.FileInfo
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.io.BufferedReader
import java.io.InputStream
import java.io.InputStreamReader
import java.io.OutputStream
import java.io.PrintWriter
import java.net.InetSocketAddress
import java.net.ServerSocket
import java.net.Socket
import kotlin.concurrent.thread

/**
 * Shared file-transfer plumbing used by BOTH group chats (P2PManager) and
 * direct member chats (DirectChatManager).
 *
 * The file bytes never travel over the message stream: the sender opens a
 * short-lived download server on a random port and shares its address in the
 * FileInfo carried by a "file_message". Receivers connect back and speak the
 * handshake:
 *
 *     receiver -> "file_download" {fileId}                          (plaintext)
 *     sender   -> ENCRYPTED LINE: AES-GCM(fileKey, file_meta JSON)
 *     sender   -> [4B ctLen][12B nonce][AES-GCM chunk]... [4B zero EOF]
 *
 * The per-file key [FileInfo.fileKey] is generated by the sender and travels
 * only inside the (itself encrypted) chat message that offered the file, so a
 * passive sniffer sees ciphertext for the meta line AND the byte stream, and
 * tampering anywhere trips the GCM tag and aborts the download.
 *
 * All socket I/O runs on worker threads; [runServer] owns the accept loop and
 * spawns one thread per served client. Servers stop when [isActive] turns
 * false or the ServerSocket is closed (a cancelled P2PManager closes it via
 * stop()).
 */
object FileTransfer {

    private const val TAG = "FileTransfer"

    /** Hard cap on a single downloaded file. Protects storage from a broken
     *  or malicious sender that streams far more than the offer declared
     *  (or declares an unknown size) — without it the app keeps writing until
     *  the peer disconnects and can fill the device. */
    const val MAX_DOWNLOAD_BYTES = 512L * 1024 * 1024

    /** A file download server lives at most this long, even when nobody
     *  downloads: previously a sent file held its ServerSocket + accept thread
     *  forever (one FD/thread per file until the process died). */
    const val FILE_SERVER_TTL_MS = 15L * 60 * 1000

    private const val CHUNK_SIZE = 64 * 1024

    /** Largest ciphertext chunk frame on the wire: plaintext + nonce + GCM
     *  tag — exactly the overhead [Crypto.aesGcmEncrypt] adds per chunk. */
    private const val MAX_CHUNK_WIRE = CHUNK_SIZE + Crypto.GCM_NONCE_LEN + Crypto.GCM_TAG_BITS / 8

    private val json = Json { ignoreUnknownKeys = true }

    /** Result of a file download. */
    data class DownloadResult(val ok: Boolean, val message: String = "")

    /**
     * Accept-loop for a download server: serve any client that completes the
     * [file_download] handshake until [isActive] turns false, the TTL elapses,
     * or the socket is closed. Removes itself from the caller's registry via
     * [onRemove]. [fileKey] encrypts the meta line and every chunk.
     */
    fun runServer(
        fileId: String,
        server: ServerSocket,
        resolver: ContentResolver,
        uri: Uri,
        fileName: String,
        fileSize: Long,
        fileKey: ByteArray,
        isActive: () -> Boolean,
        onRemove: (String) -> Unit,
        ttlMs: Long = FILE_SERVER_TTL_MS
    ) {
        thread(name = "file-server-$fileId") {
            val deadline = System.currentTimeMillis() + ttlMs
            try {
                server.soTimeout = 30_000
                while (isActive() && System.currentTimeMillis() < deadline) {
                    val client = try {
                        server.accept()
                    } catch (e: java.net.SocketTimeoutException) {
                        // idle window with no downloader: keep waiting until the
                        // TTL expires (or the server is closed / deactivated),
                        // instead of treating the timeout as a fatal error and
                        // shutting the server down ~30s after the offer
                        if (!isActive() || System.currentTimeMillis() < deadline) continue
                        break
                    } catch (e: Exception) {
                        // external closure (P2PManager.stop(), TTL) or a real error
                        Log.w(TAG, "file server accept failed", e)
                        break
                    }
                    client.tcpNoDelay = true
                    thread(name = "file-serve-$fileId") {
                        serveFile(client, fileId, fileKey, resolver, uri, fileName, fileSize)
                    }
                }
            } finally {
                onRemove(fileId)
                runCatching { server.close() }
            }
        }
    }

    private fun serveFile(
        socket: Socket,
        fileId: String,
        fileKey: ByteArray,
        resolver: ContentResolver,
        uri: Uri,
        fileName: String,
        fileSize: Long
    ) {
        try {
            socket.soTimeout = 30_000
            val reader = BufferedReader(InputStreamReader(socket.getInputStream()))
            val handshake = readLineLimited(reader) ?: return
            val req = runCatching { json.decodeFromString<NetworkPacket>(handshake) }.getOrNull()
                ?: return
            if (req.type != "file_download" || req.fileId != fileId) return
            val meta = NetworkPacket(
                type = "file_meta",
                fileInfo = FileInfo(fileId, fileName, fileSize, "", 0)
            )
            sendLine(socket, Crypto.toB64(Crypto.aesGcmEncrypt(fileKey, json.encodeToString(meta).toByteArray(Charsets.UTF_8))))
            socket.soTimeout = 120_000
            val input = resolver.openInputStream(uri) ?: return
            input.use { ins ->
                val buffer = ByteArray(CHUNK_SIZE)
                val out = socket.getOutputStream()
                while (true) {
                    val n = ins.read(buffer)
                    if (n <= 0) break
                    writeEncryptedChunk(out, fileKey, buffer, n)
                }
                // explicit EOF marker: a truncated stream is detected before
                // the completeness check, not silently accepted
                out.write(byteArrayOf(0, 0, 0, 0))
                out.flush()
            }
        } catch (e: Exception) {
            Log.w(TAG, "serveFile failed", e)
        } finally {
            closeSocket(socket)
        }
    }

    /** Frame one encrypted plaintext chunk: [4B length][nonce][ct||tag]. */
    private fun writeEncryptedChunk(out: OutputStream, key: ByteArray, buffer: ByteArray, len: Int) {
        val blob = Crypto.aesGcmEncrypt(key, buffer.copyOf(len))
        val header = ByteArray(4)
        header[0] = (blob.size ushr 24).toByte()
        header[1] = (blob.size ushr 16).toByte()
        header[2] = (blob.size ushr 8).toByte()
        header[3] = blob.size.toByte()
        out.write(header)
        out.write(blob)
    }

    /**
     * Download a file offered via [fileInfo] into [out]. Blocking; call from a
     * background thread. The meta line and every chunk are decrypted with the
     * per-file key from the (encrypted) offer; any tampering or key mismatch
     * aborts. Verifies the received byte count against the offer and aborts
     * early the moment the stream exceeds the declared size or the hard cap.
     */
    fun download(fileInfo: FileInfo, out: OutputStream): DownloadResult {
        if (fileInfo.fileSize > MAX_DOWNLOAD_BYTES) {
            return DownloadResult(false, "文件过大（超过 ${MAX_DOWNLOAD_BYTES / 1024 / 1024} MB 限制）")
        }
        val fileKey = Crypto.fromB64(fileInfo.fileKey)
        if (fileKey == null || fileKey.size != Crypto.KEY_LEN) {
            return DownloadResult(false, "文件密钥缺失或无效")
        }
        var socket: Socket? = null
        try {
            val s = Socket()
            socket = s
            s.connect(InetSocketAddress(fileInfo.downloadHost, fileInfo.downloadPort), 10_000)
            s.tcpNoDelay = true
            s.soTimeout = 10_000
            val rawIn = s.getInputStream()
            val writer = PrintWriter(s.getOutputStream(), true)
            writer.println(json.encodeToString(NetworkPacket(type = "file_download", fileId = fileInfo.fileId)))
            // read the meta line straight from the raw stream, byte by byte:
            // a BufferedReader would read-ahead and swallow the file bytes
            // that the sender streams immediately after the meta line
            val line = readRawLineLimited(rawIn) ?: return DownloadResult(false, "发送方无响应")
            val blob = Crypto.fromB64(line) ?: return DownloadResult(false, "无效的响应")
            val metaJson = try {
                Crypto.aesGcmDecrypt(fileKey, blob)
            } catch (e: Exception) {
                return DownloadResult(false, "文件密钥不匹配或数据损坏")
            }
            val meta = runCatching { json.decodeFromString<NetworkPacket>(metaJson.toString(Charsets.UTF_8)) }.getOrNull()
                ?: return DownloadResult(false, "无效的响应")
            if (meta.type != "file_meta" || meta.fileInfo == null) {
                return DownloadResult(false, "无效的响应")
            }
            if (meta.fileInfo.fileId != fileInfo.fileId) {
                return DownloadResult(false, "文件不匹配")
            }
            // The streamed size is governed by whichever declared size is
            // SMALLER: if the offer and the server's meta disagree, trust the
            // smaller defensive bound (an oversized claim must not lift the
            // cap, and an undersized claim gets caught by the completeness
            // check below).
            val offerSize = if (fileInfo.fileSize in 1..MAX_DOWNLOAD_BYTES) fileInfo.fileSize else 0L
            val metaSize = if (meta.fileInfo.fileSize in 1..MAX_DOWNLOAD_BYTES) meta.fileInfo.fileSize else 0L
            val expected = when {
                offerSize > 0 && metaSize > 0 -> minOf(offerSize, metaSize)
                offerSize > 0 -> offerSize
                metaSize > 0 -> metaSize
                else -> 0L
            }
            s.soTimeout = 120_000
            var received = 0L
            var eofMarker = false
            while (!eofMarker) {
                val header = readExact(rawIn, 4) ?: return DownloadResult(false, "文件传输中断")
                val frameLen = ((header[0].toInt() and 0xFF) shl 24) or
                    ((header[1].toInt() and 0xFF) shl 16) or
                    ((header[2].toInt() and 0xFF) shl 8) or
                    (header[3].toInt() and 0xFF)
                if (frameLen == 0) {
                    eofMarker = true
                    break
                }
                if (frameLen < Crypto.GCM_NONCE_LEN + 16 || frameLen > MAX_CHUNK_WIRE) {
                    return DownloadResult(false, "文件数据损坏")
                }
                val frame = readExact(rawIn, frameLen) ?: return DownloadResult(false, "文件传输中断")
                val plain = try {
                    Crypto.aesGcmDecrypt(fileKey, frame)
                } catch (e: Exception) {
                    return DownloadResult(false, "文件数据校验失败（可能被篡改）")
                }
                received += plain.size
                // abort before writing when the declared size is exceeded:
                // the offer is then a lie and the file would only be corrupt
                if (expected > 0 && received > expected) {
                    return DownloadResult(false, "文件大小不符（已接收 $received 字节，超过声明大小）")
                }
                if (received > MAX_DOWNLOAD_BYTES) {
                    return DownloadResult(false, "文件超过 ${MAX_DOWNLOAD_BYTES / 1024 / 1024} MB 限制")
                }
                out.write(plain, 0, plain.size)
            }
            out.flush()
            // size 0 means unknown (some content providers do not report it);
            // only verify when the target size is actually known. Using the
            // same `expected` bound as the mid-stream abort keeps both checks
            // consistent.
            if (expected > 0 && received != expected) {
                return DownloadResult(false, "文件不完整（$received/$expected 字节）")
            }
            return DownloadResult(true)
        } catch (e: Exception) {
            Log.w(TAG, "download failed", e)
            return DownloadResult(false, "下载失败: ${e.message}")
        } finally {
            closeSocket(socket)
        }
    }

    private fun readExact(input: InputStream, n: Int): ByteArray? {
        val buf = ByteArray(n)
        var read = 0
        while (read < n) {
            val got = try {
                input.read(buf, read, n - read)
            } catch (e: Exception) {
                return null
            }
            if (got < 0) return null
            read += got
        }
        return buf
    }

    /** Reads one '\n'-terminated line from the raw stream without any
     *  buffered wrapper, so bytes that follow (e.g. a file payload on the same
     *  connection) are never swallowed by read-ahead buffering. */
    private fun readRawLineLimited(input: InputStream): String? {
        var buffer = ByteArray(256)
        var size = 0
        try {
            while (size <= P2PManager.MAX_LINE_LENGTH) {
                val b = input.read()
                if (b == -1) {
                    return if (size == 0) null else String(buffer, 0, size, Charsets.UTF_8)
                }
                if (b == '\n'.code) {
                    return String(buffer, 0, size, Charsets.UTF_8).removeSuffix("\r")
                }
                if (size == buffer.size) {
                    buffer = buffer.copyOf(buffer.size * 2)
                }
                buffer[size++] = b.toByte()
            }
        } catch (e: Exception) {
            return null
        }
        return null
    }

    private fun readLineLimited(reader: BufferedReader): String? =
        P2PManager.readLineLimited(reader)

    private fun sendLine(socket: Socket, line: String) {
        runCatching {
            val writer = PrintWriter(socket.getOutputStream(), true)
            writer.println(line)
        }
    }

    private fun closeSocket(socket: Socket?) {
        socket ?: return
        runCatching { socket.close() }
    }
}
